name: Build App
on:
  workflow_dispatch:
    inputs:
      releaseStage:
        description: 'alpha, beta or production release (alpha does not upload to TestFlight)'
        required: true
        default: 'alpha'
      versionChangeType:
        description: 'Type of version bump (major, minor, patch, none)'
        required: true
        default: 'none'

jobs:
  build-app:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Setup Git
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com

      - name: Versioning
        uses: DominicSherman/mobile-release-actions/versioning@v1
        with:
          github-auth-token: ${{ secrets.GITHUB_TOKEN }}
          branch-to-tag: 'main'
          version-change-type: ${{ github.event.inputs.versionChangeType }}
          build-version: ${{ github.run_number }}
          update-eas: true

      - name: EAS build config
        uses: DominicSherman/mobile-release-actions/eas-build@v1
        with:
          apple-id: ${{ secrets.APPLE_ID }}
          apple-asc-app-id: ${{ secrets.ASC_APPLE_ID }}
          apple-team-id: ${{ secrets.APPLE_TEAM_ID }}
          android-expo-deploy-key-path: ${{ secrets.ANDROID_EXPO_DEPLOY_KEY_PATH }}
          android-submit-track: ${{ secrets.ANDROID_SUBMIT_TRACK }}
      
      # optional if you want to persist changes in the code base
      # - name: Create PR with version bump
      #   uses: peter-evans/create-pull-request@v3
      #   with:
      #     token: ${{ secrets.GITHUB_TOKEN }}
      #     branch: 'release-${{github.run_number}}'
      #     title: 'release: ${{ github.event.inputs.releaseStage }} version release'
      #     commit-message: 'release: ${{ github.event.inputs.releaseStage }} version release'
      #     author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
      #     delete-branch: true

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'yarn'

      - name: Install packages
        run: yarn install --frozen-lockfile

      - name: Install EAS CLI
        uses: expo/expo-github-action@v7
        with:
          expo-version: 5.x
          eas-version: latest
          token: ${{ secrets.EXPO_CI_TOKEN }}

      - name: Build iOS
        run: |
          eas build --platform ios --profile ${{ github.event.inputs.releaseStage }} --non-interactive --auto-submit --no-wait