name: Build App
on:
  workflow_dispatch:
    inputs:
      releaseStage:
        type: choice
        description: 'type of release'
        required: true
        default: 'alpha'
        options:
          - alpha
          - beta
          - production
      versionChangeType:
        type: choice
        description: 'type of version bump'
        required: true
        default: 'none'
        options:
          - major
          - minor
          - patch
          - none
      platform:
        type: choice
        description: 'platform to build for'
        required: true
        default: 'all'
        options:
          - all
          - ios
          - android

jobs:
  build-app:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Setup Git
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com

      - name: Tagging
        id: tagging
        uses: DominicSherman/mobile-release-actions/tagging@v1
        with:
          github-auth-token: ${{ secrets.GITHUB_TOKEN }}
          branch-to-tag: 'main'
          version-change-type: ${{ github.event.inputs.versionChangeType }}
          build-version: ${{ github.run_number }}

      - name: Update versions
        uses: DominicSherman/mobile-release-actions/update-versions@v1
        with:
          tag: ${{ steps.tagging.outputs.tag }}

      - name: EAS build config
        uses: DominicSherman/mobile-release-actions/eas-config@v1
        with:
          apple-id: ${{ secrets.APPLE_ID }}
          apple-asc-app-id: ${{ secrets.ASC_APPLE_ID }}
          apple-team-id: ${{ secrets.APPLE_TEAM_ID }}
          android-expo-deploy-key-path: ${{ secrets.ANDROID_EXPO_DEPLOY_KEY_PATH }}

      - name: Install EAS CLI
        uses: expo/expo-github-action@v7
        with:
          expo-version: 5.x
          eas-version: latest
          token: ${{ secrets.EXPO_CI_TOKEN }}

      - name: Build
        uses: DominicSherman/mobile-release-actions/eas-build@v1
        with:
          release-stage: ${{ github.event.inputs.releaseStage }}
          platform: ${{ github.event.inputs.platform }}

      # optional if you want to persist changes in the code base
      # - name: Create PR with version bump
      #   uses: peter-evans/create-pull-request@v3
      #   with:
      #     token: ${{ secrets.GITHUB_TOKEN }}
      #     branch: 'release-${{github.run_number}}'
      #     title: 'release: ${{ github.event.inputs.releaseStage }} version release'
      #     commit-message: 'release: ${{ github.event.inputs.releaseStage }} version release'
      #     author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
      #     delete-branch: true
      